service:
  name: meowbot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  env: ${file(./${opt:stage, self:provider.stage}.env.json)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3000

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  post-tweet:
    handler: handle-post-tweet.postTweet
    events:
      - schedule:
          rate: cron(0 15 ? * TUE *)
          enabled: true
          input:
            title: Dev
            feed: iamdevloper
      - schedule:
          rate: cron(0 15 ? * FRI *)
          enabled: true
          input:
            title: Consulting
            feed: CrazyMgmtCons
    environment:
      TWITTER_KEY: ${self:custom.env.TWITTER_KEY}
      DISCORD_KEY: ${self:custom.env.DISCORD_KEY}
      DISCORD_CHANNELID: ${self:custom.env.DISCORD_CHANNELID}
  post-reddit:
    handler: handle-post-reddit.postReddit
    events:
      - schedule:
          rate: cron(0 21 ? * * *)
          enabled: true
    environment:
      DISCORD_KEY: ${self:custom.env.DISCORD_KEY}
      DISCORD_CHANNELID: ${self:custom.env.DISCORD_CHANNELID}
  post-custom:
    handler: handle-post-custom.postCustom
    environment:
      DISCORD_KEY: ${self:custom.env.DISCORD_KEY}
      DISCORD_CHANNELID: ${self:custom.env.DISCORD_CHANNELID}
  check-standup:
    handler: handle-standupbot.checkStandup
    events:
      - schedule:
          rate: cron(50 13 ? * 2-6 *)
          enabled: true
      - schedule:
          rate: cron(20 13 ? * 2-6 *)
          enabled: true
    environment:
      SLACK_KEY: ${self:custom.env.SLACK_KEY}
      SLACK_STANDUP_CHANNEL: ${self:custom.env.SLACK_STANDUP_CHANNEL}
  prompt-standup:
    handler: handle-standupbot.promptStandup
    events:
      - schedule:
          rate: cron(0 13 ? * 2-6 *)
          enabled: true
    environment:
      SLACK_KEY: ${self:custom.env.SLACK_KEY}
      SLACK_STANDUP_CHANNEL: ${self:custom.env.SLACK_STANDUP_CHANNEL}
  list-standup-users:
    handler: handle-standupbot.listStandupUsers
    environment:
      SLACK_KEY: ${self:custom.env.SLACK_KEY}
      SLACK_STANDUP_CHANNEL: ${self:custom.env.SLACK_STANDUP_CHANNEL_PROD}
  

#0 20 * * * /usr/share/meowbot/dadjokes.pl
#0 14 * * 2 /usr/share/meowbot/crazytweet.pl iamdevloper Dev
#0 14 * * 5 /usr/share/meowbot/crazytweet.pl CrazyMgmtCons Consulting